//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATHI()
        {
            this.PHONGTHI = new HashSet<PHONGTHI>();
        }
    
        public int MaCaThi { get; set; }
        public string TenCaThi { get; set; }
        public System.TimeSpan GioThi { get; set; }
        public System.TimeSpan GioTapTrung { get; set; }
        public Nullable<int> MaLoai_CaThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGTHI> PHONGTHI { get; set; }
        public virtual LOAICATHI LOAICATHI { get; set; }
    }
}
