//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKY
    {
        public int MaDangKy { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public int LePhi { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaLopHoc_DangKy { get; set; }
        public Nullable<int> MaHocVien_DangKy { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
