//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINALPROJECTEntities : DbContext
    {
        public FINALPROJECTEntities()
            : base("name=FINALPROJECTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAHOC> CAHOC { get; set; }
        public virtual DbSet<CATHI> CATHI { get; set; }
        public virtual DbSet<CHAMCONG> CHAMCONG { get; set; }
        public virtual DbSet<DANGKY> DANGKY { get; set; }
        public virtual DbSet<DANHGIAKHOAHOC> DANHGIAKHOAHOC { get; set; }
        public virtual DbSet<DonXinNghi> DonXinNghi { get; set; }
        public virtual DbSet<HOCVIEN> HOCVIEN { get; set; }
        public virtual DbSet<KETQUA> KETQUA { get; set; }
        public virtual DbSet<KETQUAKHAOSAT> KETQUAKHAOSAT { get; set; }
        public virtual DbSet<KHAOSAT> KHAOSAT { get; set; }
        public virtual DbSet<KHOAHOC> KHOAHOC { get; set; }
        public virtual DbSet<LOAI> LOAI { get; set; }
        public virtual DbSet<LOAICATHI> LOAICATHI { get; set; }
        public virtual DbSet<LOAINHANVIEN> LOAINHANVIEN { get; set; }
        public virtual DbSet<LOAITHONGBAO> LOAITHONGBAO { get; set; }
        public virtual DbSet<LOP> LOP { get; set; }
        public virtual DbSet<LUONG> LUONG { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<NHAPHANG> NHAPHANG { get; set; }
        public virtual DbSet<PHIEUTHU> PHIEUTHU { get; set; }
        public virtual DbSet<PHONGHOC> PHONGHOC { get; set; }
        public virtual DbSet<PHONGTHI> PHONGTHI { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<THONGBAO> THONGBAO { get; set; }
        public virtual DbSet<YEUCAUHOCVIEN> YEUCAUHOCVIEN { get; set; }
        public virtual DbSet<YEUCAUNHANVIEN> YEUCAUNHANVIEN { get; set; }
    }
}
