//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCVIEN()
        {
            this.DANGKY = new HashSet<DANGKY>();
            this.DANHGIAKHOAHOC = new HashSet<DANHGIAKHOAHOC>();
            this.DonXinNghi = new HashSet<DonXinNghi>();
            this.KETQUA = new HashSet<KETQUA>();
            this.KETQUAKHAOSAT = new HashSet<KETQUAKHAOSAT>();
            this.PHIEUTHU = new HashSet<PHIEUTHU>();
            this.YEUCAUHOCVIEN = new HashSet<YEUCAUHOCVIEN>();
        }
    
        public int MaHocVien { get; set; }
        public string TenHocVien { get; set; }
        public string AnhDaiDien { get; set; }
        public string GioiTinh { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaTaiKhoan_HocVien { get; set; }
        public Nullable<int> MaLop_HocVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKY> DANGKY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIAKHOAHOC> DANHGIAKHOAHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonXinNghi> DonXinNghi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUA> KETQUA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUAKHAOSAT> KETQUAKHAOSAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUCAUHOCVIEN> YEUCAUHOCVIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
