//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAKHAOSAT
    {
        public int MaKetQuaKhaoSat { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayLamKhaoSat { get; set; }
        public Nullable<int> MaHocVien_KetQuaKhaoSat { get; set; }
        public Nullable<int> MaKhaoSat_KetQuaKhaoSat { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
        public virtual KHAOSAT KHAOSAT { get; set; }
    }
}
