//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public int MaKetQua { get; set; }
        public double DiemSo { get; set; }
        public string XepLoai { get; set; }
        public Nullable<int> MaHocVien_KetQua { get; set; }
        public Nullable<int> MaKhoaHoc_KetQua { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
