//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAOSAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHAOSAT()
        {
            this.KETQUAKHAOSAT = new HashSet<KETQUAKHAOSAT>();
        }
    
        public int MaKhaoSat { get; set; }
        public string TenKhaoSat { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayTaoKhaoSat { get; set; }
        public System.DateTime NgayKetThucKhaoSat { get; set; }
        public Nullable<int> MaNhanVien_KhaoSat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUAKHAOSAT> KETQUAKHAOSAT { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
