//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANG
    {
        public int MaNhapHang { get; set; }
        public string LoaiVatTu { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<int> MaNhanVien_NhapHang { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
