//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public int MaPhieuThu { get; set; }
        public int SoTien { get; set; }
        public System.DateTime NgayThu { get; set; }
        public Nullable<int> MaHocVien_PhieuThu { get; set; }
        public Nullable<int> MaKhoaHoc_PhieuThu { get; set; }
    
        public virtual HOCVIEN HOCVIEN { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
