//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGHOC()
        {
            this.LOP = new HashSet<LOP>();
            this.PHONGTHI = new HashSet<PHONGTHI>();
        }
    
        public int MaPhongHoc { get; set; }
        public string TenPhongHoc { get; set; }
        public int SucChua { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaLoaiPhong_PhongHoc { get; set; }
        public Nullable<int> MaNhanVien_PhongHoc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual LOAI LOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGTHI> PHONGTHI { get; set; }
    }
}
