//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public int MaThongBao { get; set; }
        public string NoiDung { get; set; }
        public string NguoiNhan { get; set; }
        public System.DateTime NgayGui { get; set; }
        public Nullable<int> MaNhanVien_ThongBao { get; set; }
        public Nullable<int> MaLoaiThongBao_ThongBao { get; set; }
    
        public virtual LOAITHONGBAO LOAITHONGBAO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
